# Generated by Django 5.2.8 on 2025-11-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="librarian",
            old_name="books",
            new_name="library",
        ),
    ]
